{include file="common/header"}
<div class="content-wrapper">
    {include file="member/nav"}
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    {include file="member/tabs"}
                    <div class="tab-content">
                        <div class="page-content">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    筛选
                                    <span class="pull-right">共有会员&nbsp;<font style="color: red;font-weight: bold;">{$total}</font>&nbsp;人，会员余额累计总额&nbsp;<font style="color: red;font-weight: bold;">{$credit2Total}</font>元</span>
                                </div>
                                <div class="panel-body">
                                    <form class="form-horizontal" method="get" role="form">
                                        <div class="form-group">
                                            <label class="col-xs-12 col-sm-3 col-md-2 control-label">关键词</label>
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12">
                                                <input type="text" class="form-control" name="keyword" value="{$_GET['keyword']?$_GET['keyword']:''}" placeholder="请输入会员编号、用户名、手机号关键词">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-xs-12 col-sm-3 col-md-2 control-label">状态</label>
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12">
                                                <label class="checkbox-inline">
                                                    <input type="checkbox" name="is_check[]" {if !empty($_GET['is_check']) && in_array(1,$_GET['is_check'])}checked{/if} value="1">
                                                    正常
                                                </label>
                                                <label class="checkbox-inline">
                                                    <input type="checkbox" name="is_check[]" {if !empty($_GET['is_check']) && in_array(0,$_GET['is_check'])}checked{/if} value="0">
                                                    已禁用
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12 col-md-offset-2 col-lg-offset-2 col-sm-offset-4">
                                                <button class="btn btn-primary">搜索</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>


                            <form method="post" class="form-horizontal" id="display_form">
                                <div class="panel panel-default ">
                                    <div class="table-responsive panel-body">
                                        <table class="table table-hover">
                                            <thead class="navbar-inner">
                                            <tr>
                                                <th>会员编号</th>
                                                <th>用户名</th>
                                                <th>余额</th>
                                                <th>邮箱</th>
                                                <th>商户名</th>
                                                <th>手机</th>
                                                <th>申请时间</th>
                                                <th>状态</th>
                                                <th>操作</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {if !empty($list)}
                                                {volist name="list" id="item"}
                                                <tr>
                                                    <td>
                                                        <input type="checkbox" name="ids[]" value="{$item['id']}">{$item['id']}
                                                    </td>
                                                    <td>{$item['username']}</td>
                                                    <td>
                                                        <label class="label label-primary">{$item['credit2']}</label>
                                                    </td>
                                                    <td>{$item['email']}</td>
                                                    <td>{$item['shopper_name']}</td>
                                                    <td>{$item['mobile']}</td>                                                    
                                                    <td>
                                                        {$item['create_time']}
                                                    </td>
                                                    <td>
                                                        {$item['status']}
                                                    </td>
                                                    <td>
                                                        <a class="btn btn-sm btn-success btn-act" act="enable" username={$item['username']}>启用</a>
                                                        <a class="btn btn-sm btn-success btn-act" act="disable" username={$item['username']}>禁用</a>
                                                        <a class="btn btn-sm btn-success btn-act" act="pass" username={$item['username']}>通过</a>
                                                        <a class="btn btn-sm btn-success btn-act" act="pass" username={$item['username']}>拒绝</a>
                                                    </td>
                                                </tr>
                                                {/volist}
                                                <tr>
                                                    <td>
                                                        <input type="checkbox" onclick="var ck = this.checked;$('table').find(':checkbox').each(function(){this.checked = ck});">
                                                    </td>
                                                    <td colspan="6">
                                                        <button class="btn btn-sm btn-danger" name="submit" type="button">删除</button>
                                                    </td>
                                                </tr>
                                            {/if}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </form>
                            {$pager}
                            <script type="text/javascript">
                                $(function () {
                                    $('button[name="submit"]').bind('click',function() {
                                        if (confirm('删除后不可恢复，您确定删除吗？')) {
                                            $.post(
                                                window.location.href,
                                                $('#display_form').serialize(),
                                                function (ret) {
                                                    message(ret.message, ret.redirect, ret.type);
                                                }, 'json'
                                            );
                                        }
                                    });

                                    $('.btn-act').bind('click', function () {
                                        var obj = {
                                            username : $(this).attr('username'),
                                            act: $(this).attr('act'),
                                        }
                                        if (confirm('确认对该商户进行操作吗？')) {
                                            $.post(
                                                 '/admin/shopper/post',
                                                 obj,
                                                 function (ret) {
                                                     message(ret.message, ret.redirect, ret.type);
                                                 }, 'json'
                                             );
                                        }
                                    });


                                });
                            </script>
                        </div>
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
</div>
{include file="common/footer"}
